- hosts: all
  remote_user: root
  tasks:
    - name: Install pip and docker module
      import_role:
        name: geerlingguy.pip

    - name: Add Docker GPG apt Key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker Repository
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu focal stable
        state: present

    - name: Update apt and install docker-ce
      apt:
        name: docker-ce
        state: latest
        update_cache: true

    - name: Set .env from environment.j2
      ansible.builtin.template:
        src: templates/environment.j2
        dest: ./.env
      when: '"webservers" in groups and inventory_hostname in groups["webservers"]'

    - name: Set .env from .env.example
      ansible.builtin.file:
        path: .env
        state: touch
      when: '"webservers" not in groups or inventory_hostname not in groups["webservers"]'

    - name: Deploy redmine
      community.docker.docker_container:
        name: redmine
        image: "redmine"
        restart_policy: always
        state: started
        ports:
          - 80:3000
          - 443:3000
        env_file: .env


- hosts: webservers
  remote_user: root
  tasks:
    - name: Import the Datadog Agent role from the Datadog collection
      import_role:
        name: datadog.datadog

    - name: configure http_check
      ansible.builtin.copy:
        src: ./services/datadog/conf.yml
        dest: /etc/datadog-agent/conf.d/http_check.d/conf.yaml
      notify: restart datadog agent

  handlers:
    - name: restart datadog agent
      ansible.builtin.service:
        name: datadog-agent
        state: restarted