- hosts: all
  remote_user: root
  tasks:
    - name: prepare server for deploy
      ansible.builtin.import_playbook: setup.yml

    - name: Set .env from environment.j2
      ansible.builtin.template:
        src: templates/environment.j2
        dest: ./.env
      when: '"webservers" in groups and inventory_hostname in groups["webservers"]'

    - name: Set .env from .env.example
      ansible.builtin.file:
        path: .env
        state: touch
      when: '"webservers" not in groups or inventory_hostname not in groups["webservers"]'

    - name: Deploy redmine
      community.docker.docker_container:
        name: redmine
        image: "redmine"
        restart_policy: always
        state: started
        ports:
          - 80:3000
          - 443:3000
        env_file: .env


- hosts: webservers
  remote_user: root
  tasks:
    - name: Import the Datadog Agent role from the Datadog collection
      import_role:
        name: datadog.datadog

    - name: configure http_check
      copy:
        src: services/datalog.conf.yml
        dest: /etc/datadog-agent/conf.d/http_check.yaml
      notify: restart datadog agent

  handlers:
    - name: datadog restart
      ansible.builtin.service:
        name: datadog-agent
        state: restarted