- hosts: all
  remote_user: root
  tasks:
    - name: deploy redmine
      community.docker.docker_container:
        name: redmine
        image: "redmine"
        restart_policy: always
        state: started
        ports:
          - 80:3000
          - 443:3000